### ISSUE TITLE
Application exits before Wifi connection is established yet

### ISSUE THREAD

**Issue by dovadi** [nerves-hub/nerves_hub#16]
Running firmware on a RPI0 with nerves_hub (mix nerves_hub.device burn IDENTIFIER), resulted in an early exit of the applicaion
```Elixir
[
  url: “wss://device.nerves-hub.org/socket/websocket”,
  serializer: Jason,
  ssl_verify: :verify_peer,
  socket_opts: [
    cert: “”,
    key: {:ECPrivateKey, “”},
    cacerts: [
      <<48, 130,  ...>>,
      <<48, 130,  ...>>,
      <<48, 130, ...>>
   ],
  server_name_indication: ‘device.nerves-hub.org’
]
```
```
10:47:43.365 [info]  Application nerves_hub exited: exited in: NervesHub.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (ArgumentError) argument error
            :erlang.byte_size(nil)
            (nerves_hub) lib/nerves_hub/firmware_channel.ex:8: NervesHub.FirmwareChannel.topic/0
            (nerves_hub) lib/nerves_hub/application.ex:17: NervesHub.Application.start/2
            (kernel) application_master.erl:273: :application_master.start_it_old/4

10:47:43.366 [info]  Application phoenix_channel_client exited: :stopped

10:47:43.366 [info]  Application jason exited: :stopped

10:47:43.366 [info]  Application websocket_client exited: :stopped

10:47:43.366 [info]  Application nerves_time exited: :stopped

10:47:43.367 [info]  Application muontrap exited: :stopped

10:47:43.367 [info]  Application nerves_leds exited: :stopped

10:47:43.367 [info]  Application nerves_init_gadget exited: :stopped

10:47:43.367 [info]  Application one_dhcpd exited: :stopped

10:47:43.440 [info]  Application mdns exited: :stopped

10:47:43.458 [info]  Application dns exited: :stopped

10:47:43.467 [info]  Application ring_logger exited: :stopped

10:47:43.513 [info]  Application nerves_firmware_ssh exited: :stopped

10:47:43.650 [info]  Application ssh exited: :stopped

10:47:43.770 [info]  Application nerves_network exited: :stopped

10:47:43.838 [info]  Application nerves_network_interface exited: :stopped

10:47:43.950 [info]  Application nerves_wpa_supplicant exited: :stopped

10:47:43.954 [info]  Application elixir_ale exited: :stopped

10:47:43.961 [info]  Application instream exited: :stopped

10:47:43.965 [info]  Application poolboy exited: :stopped

10:47:43.971 [info]  Application poison exited: :stopped

10:47:44.059 [info]  Application hackney exited: :stopped

10:47:44.093 [info]  Application metrics exited: :stopped

10:47:44.100 [info]  Application ssl_verify_fun exited: :stopped

10:47:44.103 [info]  Application certifi exited: :stopped

10:47:44.115 [info]  Application mimerl exited: :stopped
```

I assume this is because the Wifi connection is not established yet.

**Comment by dovadi** [comment]
Wrong conclusion, the problem here was using a older version of nerves_system_rpi0 (1.1), after updating to 1.4.0. the runtime value "nerves_fw_uuid" is now available
