### ISSUE TITLE
Only the first line of the NERVES_HUB_CERT and NERVES_HUB_KEY are set in the Nerves.Runtime.KV

### ISSUE THREAD

**Issue by dovadi** [nerves-hub/nerves_hub#20]
After burning my firmware with identifier on a RPI0

```
mix nerves_hub.device burn 0001
```

I'm not able to start my RPi0. It crashes:

```
15:29:17.647 [info]  Application nerves_hub exited: exited in: NervesHub.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in :pubkey_pem.join_entry/2
            (public_key) pubkey_pem.erl:180: :pubkey_pem.join_entry([], [])
            (public_key) pubkey_pem.erl:120: :pubkey_pem.decode_pem_entries/2
            (nerves_hub) lib/nerves_hub/certificate.ex:6: NervesHub.Certificate.pem_to_der/1
            (nerves_hub) lib/nerves_hub/socket.ex:15: NervesHub.Socket.configure/1
            (nerves_hub) lib/nerves_hub/application.ex:13: NervesHub.Application.start/2
            (kernel) application_master.erl:277: :application_master.start_it_old/4
```

I did discover that the contents of the nerves_hub_key and nerves_hub_cert in Nerves.Runtime.KV. only contain the first line of the specific files:

```
iex(9)> Nerves.Runtime.KV.get_all
%{
  "a.nerves_fw_application_part0_devpath" => "/dev/mmcblk0p3",
  "a.nerves_fw_application_part0_fstype" => "ext4",
  "a.nerves_fw_application_part0_target" => "/root",
  "a.nerves_fw_architecture" => "arm",
  "a.nerves_fw_author" => "The Nerves Team",
  "a.nerves_fw_description" => "",
  "a.nerves_fw_misc" => "",
  "a.nerves_fw_platform" => "rpi0",
  "a.nerves_fw_product" => "zero_i2c",
  "a.nerves_fw_uuid" => "14b1bcd7-b618-5cf9-dc77-3b286006628e",
  "a.nerves_fw_vcs_identifier" => "",
  "a.nerves_fw_version" => "0.1.0",
  "nerves_fw_active" => "a",
  "nerves_fw_devpath" => "/dev/mmcblk0",
  "nerves_hub_cert" => "-----BEGIN CERTIFICATE-----",
  "nerves_hub_key" => "-----BEGIN EC PRIVATE KEY-----",
  "nerves_serial_number" => "0001"
}
```

I was able to reproduce the same error with only the first line of the certificate:

```
iex(14)> NervesHub.Certificate.pem_to_der("-----BEGIN CERTIFICATE-----")
** (FunctionClauseError) no function clause matching in :pubkey_pem.join_entry/2

    The following arguments were given to :pubkey_pem.join_entry/2:

        # 1
        []

        # 2
        []

    (public_key) pubkey_pem.erl:180: :pubkey_pem.join_entry/2
    (public_key) pubkey_pem.erl:120: :pubkey_pem.decode_pem_entries/2
    (nerves_hub) lib/nerves_hub/certificate.ex:6: NervesHub.Certificate.pem_to_der/1
```

I can confirm that the whole contents of the cert and key where put in the environment variables before the burn in r176 of Mix.Tasks.NervesHub.Device

```
   def burn(identifier, opts) do 
    ...
    Shell.info("Burning firmware")
    System.put_env("NERVES_SERIAL_NUMBER", identifier)
    System.put_env("NERVES_HUB_CERT", File.read!(cert_path))
    System.put_env("NERVES_HUB_KEY", File.read!(key_path))

    IO.puts System.get_env("NERVES_HUB_KEY")
    IO.puts System.get_env("NERVES_HUB_CERT")
    
    Mix.Task.run("firmware.burn", [])
  end
```

```
mix nerves_hub.device burn 0001

Nerves environment
  MIX_TARGET:   rpi0
  MIX_ENV:      dev

NervesHub org: dovadi
Burning firmware
-----BEGIN EC PRIVATE KEY-----
[the real contents of the key]
-----END EC PRIVATE KEY-----

-----BEGIN CERTIFICATE-----
[the real contents of the cert]
-----END CERTIFICATE-----

Use 3.69 GiB memory card found at /dev/rdisk2? [Yn] y
|====================================| 100% (31.79 / 31.79) MB
Success!
```

and this is where I'm now ...... 

(BTW1: I'm using the latest version of nerves 1.3.0 and nerves_system_rpi0 1.4.0)

(BTW2: awesome work on nerves hub!)

**Comment by fhunleth** [comment]
Thanks for the super-detailed bug report!

Could you check the version of `nerves_runtime` that you're using? That issue should have been fixed in in v0.6.2.

**Comment by mobileoverlord** [comment]
Can you try to update your version of `nerves_runtime`. In order to read multi line values from the U-Boot env, the target needs to be running OTP 21 and nerves_runtime >= 0.6.0

**Comment by dovadi** [comment]
After updating nerves_runtime to v0.6.5 the problem was solved!! Thanks!
